//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace librarymanagement1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int AccessionNo { get; set; }
        public Nullable<int> BarcodeID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Subject { get; set; }
        public string Publisher { get; set; }
        public string Edition { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Pages { get; set; }
        public string Vol { get; set; }
        public string Location { get; set; }
        public string Topic { get; set; }
        public string ISBN { get; set; }
        public string Source { get; set; }
        public string Class { get; set; }
        public Nullable<int> BillNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> BookNo { get; set; }
        public Nullable<long> Cost { get; set; }
        public Nullable<System.DateTime> WithdrawlNo_Date { get; set; }
        public string Remarks { get; set; }
    }
}
 //https://localhost:44352/Models/Book.cs