//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace librarymanagement1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int AdmissionNo { get; set; }
        public string StudentName { get; set; }
        public string Class { get; set; }
        public string Section { get; set; }
        public Nullable<int> RollNo { get; set; }
        public string Route { get; set; }
        public Nullable<int> BusNo { get; set; }
        public string Caste { get; set; }
        public string Category { get; set; }
        public string House { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public Nullable<long> ContactNo { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string FName { get; set; }
        public Nullable<long> FMobile { get; set; }
        public string FEducation { get; set; }
        public string FOccupation { get; set; }
        public Nullable<System.DateTime> F_DOB { get; set; }
        public string MName { get; set; }
        public Nullable<long> MMobile { get; set; }
        public string MEducation { get; set; }
        public string MOccupation { get; set; }
        public Nullable<System.DateTime> M_DOB { get; set; }
        public Nullable<System.DateTime> Parents_Wedding_Date { get; set; }
        public string Email_Id { get; set; }
        public string NameOfSchool { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> AdmissionFormNo { get; set; }
        public Nullable<System.DateTime> DateOfAdmission { get; set; }
        public string LastExamGiven { get; set; }
        public Nullable<int> LedgerBalance { get; set; }
        public Nullable<int> FeesBalance { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Year { get; set; }
        public string Status { get; set; }
        public Nullable<double> Marks { get; set; }
        public Nullable<long> AadharCardNo { get; set; }
        public Nullable<long> Biometrics { get; set; }
        public string Board_University { get; set; }
        public Nullable<int> ChildUniqueID { get; set; }
        public Nullable<int> GRNo { get; set; }
        public string BloodGroup { get; set; }
        public string VisionLeft { get; set; }
        public string VisionRight { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Family { get; set; }
        public string DentalHygiene { get; set; }
        public Nullable<int> HostelRoomNo { get; set; }
        public Nullable<int> BedNo { get; set; }
        public Nullable<int> ScholarshipNo { get; set; }
        public string StatusInSchool { get; set; }
        public string Discontinued { get; set; }
    }
}
